theme: jekyll-theme-slate
title: SciReC2021 - Scientific Recommendation Challenge
description: co-located at the 12th ACM Conference on Bioinformatics, Computational Biology, and Health Informatics (ACM BCB)
